# ===================================================================
# Minato Global Strategy Prompt Library v2.0
# This file defines the core intent-recognition and strategic planning
# layer for Minato. It is designed with robust multilingual triggers,
# extensive synonyms, and tool-aware prompts to orchestrate Minato's
# full suite of capabilities efficiently and effectively.
# ===================================================================

# ===== META TASKS: DYNAMIC CAPABILITY EXPANSION =====
# For handling queries outside of predefined domains, enabling Minato to learn.
# ===================================================================
meta_tasks:
  - id: "domain_discovery"
    description: "Discover and create a new analytical framework for a domain not covered in existing components."
    type: "llm"
    base_score: 100
    triggers:
      - keyword: "new field"
        weight: 100
      - keyword: "unknown domain"
        weight: 100
      - keyword: "unfamiliar area"
        weight: 95
      - keyword: "emerging field"
        weight: 95
      - keyword: "specialized discipline"
        weight: 95
      - keyword: "niche topic"
        weight: 90
      - keyword: "nouveau domaine" # French
        weight: 100
      - keyword: "área desconocida" # Spanish
        weight: 100
      - keyword: "neues Fachgebiet" # German
        weight: 100
      - keyword: "新領域" # Chinese
        weight: 100
      - keyword: "新しい分野" # Japanese
        weight: 100
      - keyword: "новая область" # Russian
        weight: 100
      - keyword: "مجال جديد" # Arabic
        weight: 100
    prompt: "You are an expert methodologist encountering a query about {topic}, which is outside our predefined domains. Your task is to create a new, structured analytical framework for this domain. This framework will guide Minato's tool use.

Your output must be a comprehensive plan including:
1.  **Domain Identification:** What is the specialized field (e.g., 'Astro-physics', 'Marine Biology', 'Ancient History')?
2.  **Key Concepts & Terminology:** List the 5-7 fundamental terms someone must understand in this field.
3.  **Analytical Frameworks:** What are the standard models or methodologies used (e.g., SWOT for business, Radiocarbon Dating for archaeology)?
4.  **Key Metrics:** What are the crucial quantitative and qualitative metrics for this field?
5.  **Data Sources & Tools:** What are the authoritative sources (e.g., 'NASA Jet Propulsion Laboratory Data', 'PubMed Central')? Which of Minato's tools (`Tavily`, `BrowserTool`, `Serper`) would be best to access them?
6.  **Key Stakeholders:** Who are the important organizations, research institutions, or thought leaders?
7.  **Actionable Plan:** Based on the above, provide a step-by-step plan for Minato to analyze the user's specific query using its available tools."

# ===== STRATEGIC & COMPETITIVE INTELLIGENCE =====
# High-level business and market analysis tasks.
# ===================================================
strategic_intelligence_tasks:
  - id: "business_intelligence_overview"
    description: "Generate a comprehensive business intelligence overview of a topic or company."
    type: "orchestration"
    base_score: 50
    triggers:
      - keyword: "business intelligence"
        weight: 100
      - keyword: "business overview"
        weight: 90
      - keyword: "company deep dive"
        weight: 90
      - keyword: "market intelligence"
        weight: 85
      - keyword: "intelligence d'affaires" # French
        weight: 90
      - keyword: "inteligencia de negocio" # Spanish
        weight: 90
      - keyword: "geschäftsinformationen" # German
        weight: 90
      - keyword: "商业智能" # Chinese
        weight: 90
      - keyword: "ビジネスインテリジェンス" # Japanese
        weight: 90
      - keyword: "бизнес-аналитика" # Russian
        weight: 90
    goal: "Generate a comprehensive business intelligence overview for {topic}. **Strategy**: 1. Use `Tavily` to gather market trends and news. 2. Use `BrowserTool` to analyze the target company's website. 3. Use `Serper_WebSearchTool` to identify key competitors. 4. Synthesize all findings into a report covering market trends, competitive landscape, and growth opportunities."

  - id: "investment_memo"
    description: "Create a detailed investment memorandum for a company or project."
    type: "orchestration"
    base_score: 60
    triggers:
      - keyword: "investment memo"
        weight: 100
      - keyword: "investment analysis"
        weight: 90
      - keyword: "due diligence report"
        weight: 85
      - keyword: "deal memo"
        weight: 80
      - keyword: "mémorandum d'investissement" # French
        weight: 90
      - keyword: "memorando de inversión" # Spanish
        weight: 90
      - keyword: "investitionsmemorandum" # German
        weight: 90
      - keyword: "投资备忘录" # Chinese
        weight: 90
      - keyword: "投資メモランダム" # Japanese
        weight: 90
      - keyword: "инвестиционный меморандум" # Russian
        weight: 90
    goal: "Create a detailed investment memorandum for {topic}. **Strategy**: 1. Use `FinnhubTool` or `AlphaVantageTool` for financial data if public. 2. Use `BrowserTool` to analyze the company's product, team, and market positioning from their site. 3. Use `Tavily` to research market size and growth rates. 4. Use an LLM to structure the memo with sections for: Market Opportunity, Product/Service, Competitive Analysis, Financial Projections, and Risk Assessment."

# ===== EXECUTIVE SYNTHESIS & REPORTING =====
# Final-stage tasks for creating high-level summaries and reports.
# ===================================================
executive_synthesis_tasks:
  - id: "executive_summary"
    description: "Generate a concise executive summary of all findings."
    type: "llm"
    base_score: 70
    triggers:
      - keyword: "executive summary"
        weight: 100
      - keyword: "summary"
        weight: 80
      - keyword: "give me the bottom line"
        weight: 75
      - keyword: "brief overview"
        weight: 70
      - keyword: "résumé exécutif" # French
        weight: 90
      - keyword: "resumen ejecutivo" # Spanish
        weight: 90
      - keyword: "Zusammenfassung für die Geschäftsleitung" # German
        weight: 90
      - keyword: "执行摘要" # Chinese
        weight: 90
      - keyword: "エグゼクティブサマリー" # Japanese
        weight: 90
      - keyword: "резюме для руководства" # Russian
        weight: 90
    prompt: "Generate a concise executive summary of all gathered intelligence on {topic} in the {user_domain} domain. Focus on the most critical insights, strategic implications, and 3-4 actionable recommendations, citing the source tool for key data points."

  - id: "strategic_recommendations"
    description: "Provide clear, actionable strategic recommendations."
    type: "llm"
    base_score: 65
    triggers:
      - keyword: "strategic recommendations"
        weight: 100
      - keyword: "what should I do"
        weight: 95
      - keyword: "action plan"
        weight: 90
      - keyword: "recommandations stratégiques" # French
        weight: 90
      - keyword: "recomendaciones estratégicas" # Spanish
        weight: 90
      - keyword: "strategische Empfehlungen" # German
        weight: 90
      - keyword: "战略建议" # Chinese
        weight: 90
      - keyword: "戦略的提言" # Japanese
        weight: 90
      - keyword: "стратегические рекомендации" # Russian
        weight: 90
    prompt: "Based on all analysis performed, provide clear and actionable strategic recommendations for {topic} in the {user_domain} industry. Structure the advice into: 1. **Immediate Actions** (next 30 days), 2. **Short-Term Initiatives** (next 3-6 months), and 3. **Long-Term Strategic Positioning** (1-3 years)."

# ===== MARKET ANALYSIS & TRENDS =====
# Tasks focused on understanding the broader market.
# ===================================================
market_analysis_tasks:
  - id: "market_size_analysis"
    description: "Analyze market size (TAM, SAM, SOM) and growth potential."
    type: "orchestration"
    base_score: 60
    triggers:
      - keyword: "market size"
        weight: 100
      - keyword: "market potential"
        weight: 90
      - keyword: "how big is the market"
        weight: 85
      - keyword: "taille du marché" # French
        weight: 90
      - keyword: "tamaño del mercado" # Spanish
        weight: 90
      - keyword: "Marktgröße" # German
        weight: 90
      - keyword: "市场规模" # Chinese
        weight: 90
      - keyword: "市場規模" # Japanese
        weight: 90
      - keyword: "размер рынка" # Russian
        weight: 90
    goal: "Analyze the market size for {topic}. **Strategy**: 1. Use `Tavily` to search for market research reports and industry analyses (e.g., 'TAM for {topic}'). 2. Scrape the data using the integrated crawler. 3. Use an LLM to synthesize the findings, calculating or estimating TAM, SAM, and SOM with stated assumptions and citing sources."
    
  - id: "competitor_analysis"
    description: "Analyze competitors, their products, and market positioning."
    type: "orchestration"
    base_score: 65
    triggers:
      - keyword: "competitor analysis"
        weight: 100
      - keyword: "competitive landscape"
        weight: 95
      - keyword: "who are the rivals"
        weight: 85
      - keyword: "analyse concurrentielle" # French
        weight: 90
      - keyword: "análisis de la competencia" # Spanish
        weight: 90
      - keyword: "Wettbewerbsanalyse" # German
        weight: 90
      - keyword: "竞争对手分析" # Chinese
        weight: 90
      - keyword: "競合分析" # Japanese
        weight: 90
      - keyword: "анализ конкурентов" # Russian
        weight: 90
    goal: "Analyze the competitive landscape for {topic}. **Strategy**: 1. Use `Serper_WebSearchTool` to identify top competitors. 2. For each competitor, use `BrowserTool` to visit their website and extract key products, pricing, and marketing claims. 3. Use an LLM to create a competitor matrix comparing them on key features and market share."

# ===== FINANCIAL ANALYSIS =====
# Tasks dedicated to financial forecasting and valuation.
# ===================================================
financial_analysis_tasks:
  - id: "financial_forecast"
    description: "Create financial forecasts and projections (revenue, costs, profitability)."
    type: "code"
    runtime_environment: "python"
    base_score: 70
    triggers:
      - keyword: "financial forecast"
        weight: 100
      - keyword: "financial projections"
        weight: 95
      - keyword: "business plan numbers"
        weight: 90
      - keyword: "prévisions financières" # French
        weight: 90
      - keyword: "proyecciones financieras" # Spanish
        weight: 90
      - keyword: "Finanzprognose" # German
        weight: 90
      - keyword: "财务预测" # Chinese
        weight: 90
      - keyword: "財務予測" # Japanese
        weight: 90
      - keyword: "финансовый прогноз" # Russian
        weight: 90
    prompt: "Create a 3-year financial forecast model in Streamlit for {topic}. Use `FinnhubTool` or `AlphaVantageTool` for historical data if available. The model must have interactive sliders for key assumptions like growth rate, COGS, and operating expenses. Output should include an Income Statement, Cash Flow projection, and key charts."

  - id: "valuation_analysis"
    description: "Perform a valuation analysis of a company or asset."
    type: "orchestration"
    base_score: 75
    triggers:
      - keyword: "valuation"
        weight: 100
      - keyword: "how much is it worth"
        weight: 95
      - keyword: "business value"
        weight: 90
      - keyword: "évaluation d'entreprise" # French
        weight: 90
      - keyword: "valoración" # Spanish
        weight: 90
      - keyword: "Unternehmensbewertung" # German
        weight: 90
      - keyword: "估值" # Chinese
        weight: 90
      - keyword: "企業価値評価" # Japanese
        weight: 90
      - keyword: "оценка стоимости" # Russian
        weight: 90
    goal: "Perform a valuation analysis for {topic}. **Strategy**: 1. Use `FinnhubTool` to get financial statements. 2. Use `Tavily` to find comparable company multiples (EV/EBITDA, P/E). 3. Use an LLM to perform both a DCF analysis based on the financials and a comparable company analysis. 4. Conclude with a synthesized valuation range, explaining the rationale."

# ===== DATA & INTELLIGENCE GATHERING =====
# Core tasks for acquiring raw information from various sources.
# ===================================================
data_acquisition_tasks:
  - id: "initial_reconnaissance_search"
    description: "Perform a broad web search to get a general overview and identify key entities."
    type: "api"
    base_score: 50
    triggers:
      - keyword: "search for"
        weight: 80
      - keyword: "find information on"
        weight: 75
      - keyword: "look up"
        weight: 70
      - keyword: "rechercher" # French
        weight: 80
      - keyword: "buscar información" # Spanish
        weight: 80
      - keyword: "suchen" # German
        weight: 80
      - keyword: "搜索" # Chinese
        weight: 80
      - keyword: "検索" # Japanese
        weight: 80
      - keyword: "поиск" # Russian
        weight: 80
    tool_name: "Tavily"
    goal: "Perform a broad, advanced search for '{topic}' in the context of '{user_domain}' to understand the landscape and identify key websites and reports."

  - id: "deep_dive_investigation"
    description: "Use an automated browser to investigate specific websites, extract complex data, or perform actions."
    type: "browser"
    base_score: 55
    triggers:
      - keyword: "investigate website"
        weight: 85
      - keyword: "scrape this page"
        weight: 80
      - keyword: "analyze this URL"
        weight: 75
      - keyword: "enquêter sur ce site" # French
        weight: 85
      - keyword: "investigar este sitio web" # Spanish
        weight: 85
      - keyword: "untersuche diese Webseite" # German
        weight: 85
      - keyword: "调查这个网站" # Chinese
        weight: 85
      - keyword: "このウェブサイトを調査" # Japanese
        weight: 85
      - keyword: "исследовать этот сайт" # Russian
        weight: 85
    tool_name: "BrowserTool"
    goal: "Use the `investigate_entity` operation in `BrowserTool` to perform a deep-dive analysis of {target_url} to extract information related to {information_to_extract}."

  - id: "acquire_structured_financial_data"
    description: "Retrieve structured stock market and company financial data."
    type: "api"
    base_score: 65
    triggers:
      - keyword: "stock data"
        weight: 95
      - keyword: "financial statements for"
        weight: 90
      - keyword: "market cap of"
        weight: 85
      - keyword: "données boursières" # French
        weight: 90
      - keyword: "datos bursátiles" # Spanish
        weight: 90
      - keyword: "Börsendaten" # German
        weight: 90
      - keyword: "股市数据" # Chinese
        weight: 90
      - keyword: "株式データ" # Japanese
        weight: 90
      - keyword: "биржевые данные" # Russian
        weight: 90
    tool_name: "FinnhubTool" # Can also use AlphaVantageTool
    goal: "Retrieve key financial metrics, recent news, and quarterly financial statements for the stock ticker {topic}."

  - id: "gather_community_chatter"
    description: "Gather conversations and sentiment from community platforms like Reddit and Hacker News."
    type: "orchestration"
    base_score: 60
    triggers:
      - keyword: "what are people saying on reddit"
        weight: 95
      - keyword: "hacker news sentiment"
        weight: 90
      - keyword: "forum discussion"
        weight: 80
      - keyword: "que dit-on sur reddit" # French
        weight: 90
      - keyword: "qué dice la gente en reddit" # Spanish
        weight: 90
      - keyword: "was sagen die Leute auf Reddit" # German
        weight: 90
      - keyword: "Reddit上的讨论" # Chinese
        weight: 90
      - keyword: "Redditでの評判" # Japanese
        weight: 90
      - keyword: "что говорят на Reddit" # Russian
        weight: 90
    goal: "Gather community sentiment on {topic}. **Strategy**: 1. Use `RedditTool` to search for relevant subreddits and top posts. 2. Use `HackerNewsTool` to search for threads. 3. Use an LLM to summarize the key themes, common complaints, and desired features mentioned in the communities."
    
# ===== VISUALIZATION & INTERACTIVE REPORTS =====
# Tasks for creating the final 'Living Dossier' output.
# ===================================================
reporting_and_visualization_tasks:
  - id: "interactive_dashboard"
    description: "Create a comprehensive, interactive dashboard to present all findings."
    type: "code"
    base_score: 80
    triggers:
      - keyword: "dashboard"
        weight: 100
      - keyword: "interactive report"
        weight: 95
      - keyword: "visualize the data"
        weight: 90
      - keyword: "tableau de bord interactif" # French
        weight: 90
      - keyword: "panel de control interactivo" # Spanish
        weight: 90
      - keyword: "interaktives Dashboard" # German
        weight: 90
      - keyword: "交互式仪表板" # Chinese
        weight: 90
      - keyword: "インタラクティブダッシュボード" # Japanese
        weight: 90
      - keyword: "интерактивная панель мониторинга" # Russian
        weight: 90
    runtime_environment: "streamlit"
    prompt: "Create a comprehensive, multi-page interactive dashboard in Streamlit to visualize all key data and insights about {topic}. The dashboard must include separate pages for Market Analysis, Competitor Landscape, Financials, and Lead Generation, using Plotly for charts and Ag-Grid for interactive tables."

  - id: "generate_presentation_slides"
    description: "Generate a slide deck presentation of the key findings."
    type: "llm"
    base_score: 75
    triggers:
      - keyword: "presentation"
        weight: 90
      - keyword: "slide deck"
        weight: 85
      - keyword: "powerpoint" # Common synonym
        weight: 85
      - keyword: "présentation" # French
        weight: 90
      - keyword: "presentación" # Spanish
        weight: 90
      - keyword: "Präsentation" # German
        weight: 90
      - keyword: "演示文稿" # Chinese
        weight: 90
      - keyword: "プレゼンテーション" # Japanese
        weight: 90
      - keyword: "презентация" # Russian
        weight: 90
    prompt: "Based on the Executive Summary and all gathered data, generate the content for a 10-slide presentation deck. Provide a title and 3-4 bullet points for each slide. The slide structure should be: 1. Title, 2. Executive Summary, 3. The Core Problem, 4. Market Opportunity, 5. Competitive Landscape, 6. Our Solution/Strategy, 7. Financial Outlook, 8. Key Risks, 9. Strategic Recommendations, 10. Q&A / Next Steps."